# Generated by Django 3.1.5 on 2021-02-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('persons', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=25)),
                ('emailID', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('date_of_birth', models.DateTimeField(verbose_name='date published')),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=30)),
                ('hotel_address', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('total_rooms', models.IntegerField()),
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=20)),
                ('capacity_of_person', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtestingapp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtestingapp.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbtestingapp.customer'),
        ),
    ]
