# Generated by Django 3.1.5 on 2021-03-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=30)),
                ('hotel_address', models.CharField(max_length=200)),
                ('contact_no', models.IntegerField()),
                ('email_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('total_rooms', models.IntegerField()),
                ('room_no', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=20)),
                ('capacity_of_person', models.IntegerField(default=1)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
