# Generated by Django 3.1.5 on 2021-03-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=25)),
                ('emailID', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('date_of_birth', models.DateTimeField(verbose_name='date published')),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
